import os
os.chdir("/home/mca/Desktop/SURAJ-MCA/PYTHON/C05")
f=open("abc.txt","w")
seq=("first line\n","second line\n","third line\n")
f.writelines(seq)
f.close()
f=open("abc.txt","r")
line=f.readlines()
print("Line :",line)
f.close()
